[inputs]
# === Define dimensions in dictionary format === #
# (i.e., { time = "time_counter", i = "x", j = "y"} where the
# key is the standard CMORISED dimension name and the value is the
# corresponding dimension name in all input datasets).
dimensions = { time = "time", i = "i", j = "j"}

# === Define data directory === #
# Data directory for all input datasets to be optionally substituted in filepaths below:
# (i.e., any instance of "{data_dir}" in filepaths below will be replaced with the value specified here).
#data_dir = "path/to/myESM/r1i1p1f1/SImon"
data_dir = "/nird/datalake/NS2980K/projects/TipESM/cmor/esm-up2p0-swl4p0-50y-dn2p0/v20251015"

    [inputs.mask]
    # === Define variable name & filepath of regional mask to perform sea ice mass budget === #
    name = "mask_NH"
    filepath = "/nird/datalake/NS2980K/projects/TipESM/cice_Ofx/hemisphere_masks_CICE_Ofx_NorESM2-LM.nc"

    [inputs.areacello]
    # === Define variable name & filepath of horizontal grid cell area (areacello) === #
    name = "areacello"
    filepath = "/nird/datalake/NS2980K/projects/TipESM/cice_Ofx/areacello_CICE_Ofx_NorESM2-LM_esm-piControl_r1i1p1f1_gn.nc"

    [inputs.simass]
    # === Define variable name & filepath of sea ice mass (simass) === #
    name = "simass"
    filepath = "{data_dir}/simass_SImon_NorESM2-LM_esm-up2p0-swl4p0-50y-dn2p0_r1i1p1f1_gn*.nc"

    [inputs.sidmassth]
    # === Define variable name & filepath of sea ice mass change from thermodynamics (sidmassth) === #
    name = "sidmassth"
    filepath = "{data_dir}/sidmassth_SImon_NorESM2-LM_esm-up2p0-swl4p0-50y-dn2p0_r1i1p1f1_gn*.nc"

    [inputs.sidmassdyn]
    # === Define variable name & filepath of sea ice mass change from dynamics (sidmassdyn) === #
    name = "sidmassdyn"
    filepath = "{data_dir}/sidmassdyn_SImon_NorESM2-LM_esm-up2p0-swl4p0-50y-dn2p0_r1i1p1f1_gn*.nc"

    [inputs.sidmassgrowthwat]
    # === Define variable name & filepath of sea ice mass change through growth in supercooled open water (a.k.a. frazil) (sidmassgrowthwat) === #
    name = "sidmassgrowthwat"
    filepath = "{data_dir}/sidmassgrowthwat_SImon_NorESM2-LM_esm-up2p0-swl4p0-50y-dn2p0_r1i1p1f1_gn*.nc"

    [inputs.sidmassgrowthbot]
    # === Define variable name & filepath of sea ice mass change through basal growth (sidmassgrowthbot) === #
    name = "sidmassgrowthbot"
    filepath = "{data_dir}/sidmassgrowthbot_SImon_NorESM2-LM_esm-up2p0-swl4p0-50y-dn2p0_r1i1p1f1_gn*.nc"

    [inputs.sidmasssi]
    # === Define variable name & filepath of sea ice mass change through snow-to-ice conversion (sidmasssi) === #
    name = "sidmasssi"
    filepath = "{data_dir}/sidmasssi_SImon_NorESM2-LM_esm-up2p0-swl4p0-50y-dn2p0_r1i1p1f1_gn*.nc"

    [inputs.sidmassevapsubl]
    # === Define variable name & filepath of sea ice mass change through evaporation and sublimation (sidmassevapsubl) === #
    name = "sidmassevapsubl"
    filepath = "{data_dir}/sidmassevapsubl_SImon_NorESM2-LM_esm-up2p0-swl4p0-50y-dn2p0_r1i1p1f1_gn*.nc"

    [inputs.sidmassmelttop]
    # === Define variable name & filepath of sea ice mass change through surface melting (sidmassmelttop) === #
    name = "sidmassmelttop"
    filepath = "{data_dir}/sidmassmelttop_SImon_NorESM2-LM_esm-up2p0-swl4p0-50y-dn2p0_r1i1p1f1_gn*.nc"

    [inputs.sidmassmeltbot]
    # === Define variable name & filepath of sea ice mass change through bottom melting (sidmassmeltbot) === #
    name = "sidmassmeltbot"
    filepath = "{data_dir}/sidmassmeltbot_SImon_NorESM2-LM_esm-up2p0-swl4p0-50y-dn2p0_r1i1p1f1_gn*.nc"

    [inputs.sidmasslat]
    # === Define variable name & filepath of sea ice mass change through lateral melting (sidmasslat) === #
    name = "sidmasslat"
    filepath = "{data_dir}/sidmasslat_SImon_NorESM2-LM_esm-up2p0-swl4p0-50y-dn2p0_r1i1p1f1_gn*.nc"

[outputs]
# Define Sea Ice Mass Budget Analysis netCDF output file:
output_dir = "/nird/datalake/NS2980K/projects/TipESM/SIMBA_out"
output_name = "NorESM2-LM_SIMBA_NH_esm-up2p0-swl4p0-50y-dn2p0_r1i1p1f1"
date_format = "M"
